# Generated by Django 5.0.2 on 2024-03-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="appModel",
            fields=[
                ("eid", models.IntegerField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=25)),
                ("esal", models.CharField(max_length=25)),
                ("ecity", models.CharField(max_length=25)),
                ("econtact", models.CharField(max_length=25)),
                ("edepart", models.CharField(max_length=25)),
            ],
        ),
    ]
